### ISSUE TITLE
Normalización de espectros

### ISSUE THREAD

**Issue by opcruz** [opcruz/gaiaDR3ML#2]

**Comment by fatima2112** [comment]
Hemos estado trabajando en la normalización y encontramos la siguiente explicación https://www.researchgate.net/post/How_to_normalize_the_emission_and_absorption_intensity y ya siguiendo esa formula y lo que recuerdo de lo que había mencionado la doctora de que los valores normalizado se encuentran entre 0 y 1 logramos hacer que el flujo o intensidad se establecieran entre esos valores. Al final eliminamos el ruido y nos salió un espectro normalizado.

**Comment by opcruz** [comment]
Se logró normalizar los espectros. Ver ejemplo [Normalization](https://github.com/opcruz/gaiaDR3ML/blob/7c68c535361fe69cb6992bd8e32581ecfbe355fd/GaiaXpy/Normalization.ipynb)
